### ISSUE TITLE
We need a new name

### ISSUE THREAD

**Issue by remiolsen** [SciLifeLab/de_novo_scilife#19]
Because "De novo scilife" is a silly name for any piece of software. Any suggestions?

**Comment by ewels** [comment]
`Genome Assembly`?
`Genome Assembler`?
`Assemblatron 3000`?

**Comment by guillermo-carrasco** [comment]
`DeNovoScilife`?

**Comment by guillermo-carrasco** [comment]
haha no, just kidding, I don't know, I only know that I was thinking the same as for `pm`...

**Comment by remiolsen** [comment]
@ewels You just gave me the brilliant idea of "**G**enome **A**ssembly **T**ool**K**it" But that's already taken :grin:

**Comment by vezzi** [comment]
Genome Assembly Tool Box --> GAT-Box

**Comment by remiolsen** [comment]
@vezzi I like it. Reminds me of this archaic slang word:
http://dictionary.reference.com/browse/git-box

**Comment by ewels** [comment]
**G**enome
**A**ssembly
**R**eal
**B**ase
**A**lignment
**G**eneral
**E**lucidation tool?

**G**enome
**N**ucleotide
**A**ssembly
**R**eal-time;
**L**atency?
**Y**esterday

**Comment by ewels** [comment]
Amazingly, my `Assemblatron 3000` idea is out because the name is already taken: http://assemblathon.org/

![assemblaton](http://static.tumblr.com/9eab7f7078bea7d3d98cce0f8e5760e5/sp0jcog/L8Hmj4is4/tumblr_static_assemblathon_banner_940_px.png)

**Comment by guillermo-carrasco** [comment]
no more ideas? Come on TACA took only one day to decide ;-)

**Comment by remiolsen** [comment]
@guillermo-carrasco You had some ideas from norse mythology for what is now TACA... I've always liked the word **ginnungagap**

**Comment by guillermo-carrasco** [comment]
haha well, at least I committed to something :-D. ginnungagap actually makes sense "the void that it was before the first assembly" I like it... a pity that it is unpronounceable

**Comment by pekrau** [comment]
Unpronounceable? Ha, you just have to practice a little. http://www.forvo.com/word/ginnungagap/ http://www.omnilexica.com/pronunciation/?q=Ginnungagap#.VQcHF8rd_CI

**Comment by vezzi** [comment]
Possible name:
ADA-NGI (automated De Novo Assembly NGI)
DNATB-NGI (De Novo Assembly Tool Box NGI)

**Comment by remiolsen** [comment]
My only suggestion:
NouGAT - NGI Genome Assembly Toolbox (With ou being meaningless :smirk:)

**Comment by pekrau** [comment]
I vote for NouGAT. Sticky and bad for you, but oh so good.

**Comment by mariogiov** [comment]
If you could think of a word that starts with "E", you could use NGI dnTAPE: "NGI de novo Tool Analysis Pipelin(E)"?
Maybe "E" is Environment? I don't know. I suppose "A" could be "Assembly" as well.
I wanted to suggest something with "Duct Tape" but it's too many letters.

**Comment by ewels** [comment]
NouGAT - NGI Open Universal Genome Assembly Toolbox?

**Comment by mariogiov** [comment]
NGIY ourmom Genome Assembly Toolbox
